#Services define os serviços que serão executados no ambiente Docker.
services:

  app:
    #build define o diretorio atual como aquele onde a imagem será construída.
    build: .

    #command define o comando que será executado quando o contêiner for iniciado. 
    # Executa o script seed.py para popular o banco de dados e, em seguida, inicia a aplicação Flask (app.py).
    command: sh -c "python seed.py && python app.py"

    #ports define a porta que será exposta pelo contêiner e mapeada para a porta do host.
    ports:
      - "5000:5000"

    #depends_on: antes de iniciar o serviço app, o serviço api deve ser iniciado primeiro.
    depends_on:
      - api

    #environment define variáveis de ambiente que serão passadas para o contêiner.
    #Neste caso, a variável API_URL é definida com o valor http://api:5001/agendamentos,
    # que será usada pelo serviço app para se comunicar com o serviço api.
    environment:
      API_URL: http://api:5001/agendamentos


  api:

    build: .

    command: python api.py

    ports:
      - "5001:5001"